### ISSUE TITLE
Error in Bigbluebutton 2.3

### ISSUE THREAD

**Issue by misisol** [mconf/bigbluebot#28]
I've done the instructions, but on running with node run.js, it shows errors : 

```
2021-06-05T07:14:14.105Z Missing locale messages
INFO 	2021-06-05T07:14:16.267Z Adeline Conroy: join https://HOST at 139edecb-8745-3348-9a03-108cc875aca9
ERROR 	2021-06-05T07:14:31.685Z TypeError: Cannot read property 'app.navBar.settingsDropdown.optionsLabel' of undefined
    at localize (/Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/util.js:106:41)
    at translate (/Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/util.js:113:24)
    at Object.join (/Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/util.js:146:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/run.js:49:22
    at async Promise.all (index 0)
    at async /Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/run.js:61:7
    at async Promise.all (index 0)
    at async Object.run (/Users/m/Downloads/bigbluebot-master/node_modules/bigbluebot/lib/run.js:81:3) 
```

my run.js file :
```
const bigbluebot = require('bigbluebot');

const actions = async page => {
  await bigbluebot.audio.modal.microphone(page);
  await bigbluebot.video.join(page);
  await bigbluebot.chat.send(page);
};

const options = {
  host: 'https://HOST',
  secret: 'lMb0dEpjRiRBMaelsd',
  version: '2.3',
  room: '139edecb-8745-3348-9a03-108cddaca9',
  password: {
    moderator: '212d19c0',
    attendee: 'ebaeca5c',
  },
  moderator: false,
  userdata: {
    "userdata-bbb_first_userdata": true,
    "userdata-bbb_second_userdata": true,
    "userdata-bbb_third_userdata": true,
  },
};

bigbluebot.run(actions, options);
```

**Comment by pedrobmarin** [comment]
Hi @misisol ,

- Is your bigbluebutton server running a different default locale than `en`?
- Did you changed bigbluebot version to run `2.3`?
https://github.com/mconf/bigbluebot/blob/2a9483fb87d3ff214d7b187dbb4533983a307359/config/config.json#L4
