### ISSUE TITLE
ERROR BBB Chat

### ISSUE THREAD

**Issue by MKorost** [mconf/bigbluebot#32]
Hello,
I try connecting the BigBlueBot to the Chat.

This is the error message that i get

> INFO    2021-08-10T17:10:41.059Z Bots: 1
> INFO    2021-08-10T17:10:41.060Z Life: 60 seconds
> INFO    2021-08-10T17:10:41.060Z Creating meeting
> INFO    2021-08-10T17:10:41.238Z Fetching en_GB locale
> INFO    2021-08-10T17:10:43.522Z Maryam Dietrich: join https://bbb.gerwinski.de at random-5840966
> INFO    2021-08-10T17:10:48.208Z Maryam Dietrich: perform audio modal close
> PASS    2021-08-10T17:10:50.231Z Maryam Dietrich: audio modal close
> INFO    2021-08-10T17:10:51.232Z Maryam Dietrich: perform main panel open
> FAIL    2021-08-10T17:10:55.271Z Maryam Dietrich: main panel open
> INFO    2021-08-10T17:10:56.272Z Maryam Dietrich: perform chat open
> ERROR   2021-08-10T17:11:56.273Z { TimeoutError: waiting for selector `[aria-label^="Public Chat"]` failed: timeout 60000ms exceeded
>     at new WaitTask (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
>     at DOMWorld.waitForSelectorInPage (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
>     at Object.internalHandler.waitFor (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
>     at DOMWorld.waitForSelector (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
>     at Frame.waitForSelector (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
>     at Page.waitForSelector (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1280:33)
>     at Object.click (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/bigbluebot/lib/util.js:78:16)
>     at Object.execute (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/bigbluebot/lib/action/chat.js:19:41)
>     at perform (/home/mark/Bunker/WebDev/BigBlueBot/node_modules/bigbluebot/lib/action/perform.js:37:18) name: 'TimeoutError' }

This is the code I tried

```
const bigbluebot = require('bigbluebot');

const options = {
    host: '',
    secret: '',
    version: '2.3',
    room: 'random-5840966',
    password:{
        moderator:'',
        attendee: ''
    }
};

const action = async page => {
    await bigbluebot.chat.send(page);
};


 bigbluebot.run(action, options);
```
Thanks in advance

Regards
Mark

**Comment by pedrobmarin** [comment]
Hi @MKorost 

I couldn't reproduce this issue. Could you give some extra details on the version of the bot you are using along with some more details on your bigbluebutton instance? Something like version, if there is any sort of custom configuration...

**Comment by MKorost** [comment]
@pedrobmarin,

I'm using the latest version for the bot, v2.1.0.
The BBB-Server's currently running on version 2.4-alpha-2.
As far as I know there are no custom configurations made.

**Comment by pedrobmarin** [comment]
Hmmm, thanks for the feedback @MKorost . I did not test it on 2.4. I'll take a closer look.

**Comment by pedrobmarin** [comment]
Yeah, I got it.

v2.4 removed some of the aria-labels we used to build the selectors for the bots... I'll have to dig deeper on that.

So, as the result, the bot joins, closes the audio modal and can't recognize that the user-list is already opened because it does not find that aria-label. So, following it's regular procedure, it clicks the user-list toggle and closes it.

**Comment by MKorost** [comment]
Thank you very much,

the bot is now joining and sending messages into the chat.
